name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - run: bun install --frozen-lockfile --ignore-scripts
      - run: bun run build
